### ISSUE TITLE
Understand how enrollment data in Theresa's figure will be used

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#103]
This came up during the broader TIN meeting (100+ members): 
”a lot of excitement around the website”
More Context --
DOSE study pilot - trying to get TIN group to collaborate, but don't have any platform for sharing about information for these studies
show where each of the sites are, enrollment curve

**Comment by davidborland** [comment]
1. Good to be able to tell at a glance for a given month if ahead/behind schedule for subject and site enrollment.
2. Tooltips/ability to show detailed info for each data point would be good
3. Showing number of sites to add over time to catch up to enrollment would be cool feature (based on the enrollment per site per month rate in the Excel workbook)
