### ISSUE TITLE
[queries] Approved by the PAT for a <service – i.e. CIRB>

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#13]
Number approved by the PAT for a <service – i.e. CIRB>:
- [x]       Overall
- [x]      By Fiscal Year (July 1, 2016 – June 30, 2017 (Year1), July 1, 2017 – June 30, 2018 (Year2) . . . )
- [x]      By Month
- [x]      By Institution submitted
- [x]      By Institution assigned to (i.e. which TIC/RIC)
- [x]      By Therapeutic Area
All of the above should be available with a breakout of what the funding status was at the time of approval:  funded and not funded (so for instance how many CIRB services were approved for UNC where the study was funded; how many CIRB services at UNC were approved where the study is pending funding; how many CIRB services at UNC were approved where the study was not funded).  As well as current funding status.

**Comment by krobasky** [comment]
@mbwatson, go ahead and close this ticket if the PMD already answers every question.

If the PMD only answers some of the questions posed in this ticket, check those boxes & please work with @rajshruti18 to identify what will be necessary to answer the rest.

If the question itself is unclear, even after speaking with Shruti and @xu-hao, please make a trello card on the 'Challenges' board to ensure we address the question at the next meeting.

**Comment by rajshruti18** [comment]
**Number approved by PAT for a service (overall):**
SELECT COUNT(*)
FROM proposal
WHERE
protocol_status='5' or protocol_status='55' or protocol_status='70';

**Comment by rajshruti18** [comment]
**Count of proposals approved by PAT for a service by institution submitted:**
SELECT COUNT(*),name2.description as org_name
FROM proposal
INNER JOIN name as name2 on name2.index=cast(proposal.org_name as varchar) and name2."column"='org_name'
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and (proposal.protocol_status='5' or protocol_status='55' or protocol_status='70')
GROUP BY name2.description;

**Comment by rajshruti18** [comment]
**Count of proposals approved by PAT for a service by institution assigned to:**
SELECT COUNT(*),name2.description as tic_ric_assign
FROM proposal
INNER JOIN name as name2 on name2.index=cast(proposal.tic_ric_assign_v2 as varchar) and name2."column"='tic_ric_assign_v2'
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and (proposal.protocol_status='5' or protocol_status='55' or protocol_status='70')
GROUP BY name2.description;

**Comment by rajshruti18** [comment]
**Count of proposals submitted for a service by therapeutic area:**
SELECT COUNT(*),name2.description as therapeutic_area
FROM proposal
INNER JOIN study on proposal.proposal_id=study.proposal_id
INNER JOIN name as name2 on name2.index=cast(study.theraputic_area as varchar) and name2."column"='theraputic_area'
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and (proposal.protocol_status='5' or protocol_status='55' or protocol_status='70')
GROUP BY name2.description;

**Comment by rajshruti18** [comment]
**Count of proposals approved by PAT for service by year:**
SELECT COUNT(*),extract(year from vote.meeting_date_2) as year
FROM proposal 
INNER JOIN vote on proposal.proposal_id=vote.proposal_id
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and (proposal.protocol_status='5' or protocol_status='55' or protocol_status='70')
GROUP BY year
ORDER BY year;

**Comment by rajshruti18** [comment]
**Count of proposals approved by PAT for service by year:**
SELECT COUNT(*),extract(month from vote.meeting_date_2) as month
FROM proposal
INNER JOIN vote on proposal.proposal_id=vote.proposal_id
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and (proposal.protocol_status='5' or protocol_status='55' or protocol_status='70')
GROUP BY month
ORDER BY month;

**Comment by krobasky** [comment]
@mbwatson to talk to @rajshruti18 and @xu-hao to determine if this can be ascertained from the current proposal table (stage-pmd.renci.org)

**Comment by mbwatson** [comment]
All the individual items can be answered with the Dashboard as of now.

However, @rajshruti18, do we have the necessary information to be able to answer the last piece of the request?

> All of the above should be available with a breakout of what the funding status was at the time of approval: funded and not funded (so for instance how many CIRB services were approved for UNC where the study was funded; how many CIRB services at UNC were approved where the study is pending funding; how many CIRB services at UNC were approved where the study was not funded). As well as current funding status.

**Comment by rajshruti18** [comment]
@mbwatson There is a field called 'currentFunding' in 'ProposalFunding' table that tells whether the study has been funded or not. Therefore, you can answer the piece of the query that asks about the funding status of the proposal at the time of approval but there is no field to capture a proposal's current funding status. **FYI** there is a field in REDCap called 'new_funding_source' that captures a proposal's new funding status but this field has not been mapped in the new schema. Do you want me to map this field as well?

**Comment by mbwatson** [comment]
@rajshruti18 yes, i suppose we should make the `new_funding_source` field available in the new schema so we can at least satisfy that portion of the request.

how is that information encoded--as an integer indicating status that will need to be looked up in the `name` table?

**Comment by rajshruti18** [comment]
@mbwatson I've added 'new_funding_source' field in the schema, it is named 'newFundingStatus' in the new schema. I've also requested @xu-hao to update the pipeline accordingly and yes, the information in this field is encoded as an integer indicating status that will need to be looked up in the 'name' table.

**Comment by mbwatson** [comment]
i probably should have closed this earlier, but the proposal expansion panels in the proposal tables show both the funding status and the funding status at the time of approval.
