### ISSUE TITLE
[queries] Submitted for a <service – i.e. CIRB – for ‘other’ should be noted combined as well as each item separate if possible’>

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#14]
Number submitted for a <service – i.e. CIRB – for ‘other’ should be noted combined as well as each item separate if possible’>
- [x]       Overall
- [x]       By Fiscal Year (July 1, 2016 – June 30, 2017 (Year1), July 1, 2017 – June 30, 2018 (Year2) . . . )
- [x]       By Month
- [x]       By Institution submitted
- [x]       By Institution assigned to (i.e. which TIC/RIC)
- [x]       By Therapeutic Area

All of the above should be available with a breakout of what the funding status was at the time of submission.

**Comment by krobasky** [comment]
@mbwatson, go ahead and close this ticket if the PMD already answers every question.

If the PMD only answers some of the questions posed in this ticket, check those boxes & please work with @rajshruti18 to identify what will be necessary to answer the rest.

If the question itself is unclear, even after speaking with Shruti and @xu-hao, please make a trello card on the 'Challenges' board to ensure we address the question at the next meeting.

**Comment by rajshruti18** [comment]
**Number submitted for a service (overall):**
SELECT COUNT(*)
FROM proposal
WHERE
conso_or_services='2';

**Comment by rajshruti18** [comment]
**Count of proposals submitted for a service by institution submitted:**
SELECT COUNT(*),name2.description as org_name
FROM proposal
INNER JOIN name as name2 on name2.index=cast(proposal.org_name as varchar) and name2."column"='org_name'
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and proposal.conso_or_services='2'
GROUP BY name2.description;

**Comment by rajshruti18** [comment]
**Count of proposals submitted for a service by institution assigned to:**
SELECT COUNT(*),name2.description as tic_ric_assign
FROM proposal
INNER JOIN name as name2 on name2.index=cast(proposal.tic_ric_assign_v2 as varchar) and name2."column"='tic_ric_assign_v2'
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and proposal.conso_or_services='2'
GROUP BY name2.description;

**Comment by rajshruti18** [comment]
**Count of proposals submitted for a service by therapeutic area:**
SELECT COUNT(*),name2.description as therapeutic_area
FROM proposal
INNER JOIN study on proposal.proposal_id=study.proposal_id
INNER JOIN name as name2 on name2.index=cast(study.theraputic_area as varchar) and name2."column"='theraputic_area'
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and proposal.conso_or_services='2'
GROUP BY name2.description;

**Comment by rajshruti18** [comment]
**Count of proposals submitted for a service by year:**
SELECT COUNT(*),extract(year from prop_submit) as year
FROM proposal
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and proposal.conso_or_services='2'
GROUP BY year
ORDER BY year;

**Comment by rajshruti18** [comment]
**Count of proposals submitted for a service by month:**
SELECT COUNT(*),extract(month from prop_submit) as month
FROM proposal
WHERE
proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and proposal.conso_or_services='2'
GROUP BY month
ORDER BY month;

**Comment by mbwatson** [comment]
the back-end work is done on this -- it remains to be shown on the front-end. coming soon.
