### ISSUE TITLE
[queries] Days between

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#18]
"Days between"
query output should be per proposal:  
- TIC/RIC assigned, 
- proposal_id, 
- proposal name, 
- submitting institution, 
- date1, 
- date2, 
- difference

Report 'days between':
- [x]       Submission and PAT approval (all submissions)
- [ ]       Submission and services ongoing (services only – broken out by service)
- [x]       PAT approval and grant submission (comprehensive only)
- [x]       Submission to TIN and grant submission (comprehensive only)
- [x]       Grant submission to awarded/approved (comprehensive only)

**Comment by krobasky** [comment]
@mbwatson, go ahead and close this ticket if the PMD already answers every question.

If the PMD only answers some of the questions posed in this ticket, check those boxes & please work with @rajshruti18 to identify what will be necessary to answer the rest.

If the question itself is unclear, even after speaking with Shruti and @xu-hao, please make a trello card on the 'Challenges' board to ensure we address the question at the next meeting.

**Comment by mbwatson** [comment]
I'm writing to make a note (for myself) that I've reached out to @rajshruti18 for help on this one.

**Comment by xu-hao** [comment]
Days between Submission and PAT approval (all submissions)
SELECT 
    DATE_PART('day', meeting_date_2 :: timestamp - proposal.prop_submit :: timestamp),
    proposal.proposal_id,
    proposal.tic_ric_assign_v2,
    proposal.short_name,
    proposal.org_name,
    proposal.prop_submit,
    meeting_date_2,
    name.description as protocol_status
FROM proposal  
INNER JOIN vote ON proposal.proposal_id = vote.proposal_id
INNER JOIN name ON name.index=CAST(proposal.protocol_status AS VARCHAR) AND name."column"='protocol_status'
WHERE proposal.protocol_status NOT IN ('3', '40') and proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and meeting_date_2 is not null
ORDER BY proposal.proposal_id;

**Comment by mbwatson** [comment]
Thanks for this @xu-hao 

I've changed it to pull in the actual `tic_name` and the `org_name` of each proposal instead of the encoded integers. I also added in `therapeutic_area`.

```
`SELECT 
            CAST(proposal2.proposal_id AS INT),
            proposal2.short_name,
            name2.description AS tic_name,
            name3.description AS org_name,
            name4.description AS therapeutic_area,
            proposal2.prop_submit,
            meeting_date_2,
            name.description AS proposal_status,
            DATE_PART('day', meeting_date_2 :: timestamp - proposal2.prop_submit :: timestamp) AS day_count
        FROM (SELECT *, COALESCE(proposal.tic_ric_assign_v2, proposal.tic_ric_assign) AS tic_ric_assign2 from proposal) proposal2  
        INNER JOIN vote ON proposal2.proposal_id = vote.proposal_id
        INNER JOIN name ON name.index=CAST(proposal2.protocol_status AS VARCHAR) AND name."column"='protocol_status'
        INNER JOIN name name2 ON name2.index=CAST(proposal2.tic_ric_assign_v2 AS VARCHAR)
        INNER JOIN name name3 ON name3.index=CAST(proposal2.org_name AS VARCHAR)
        INNER JOIN study ON proposal2.proposal_id=study.proposal_id
        INNER JOIN name name4 ON name4.index=CAST(study.theraputic_area AS VARCHAR)
        WHERE proposal2.protocol_status NOT IN ('3', '40')
          AND proposal2.redcap_repeat_instrument IS NULL
          AND proposal2.redcap_repeat_instance IS NULL
          AND meeting_date_2 IS NOT NULL
          AND name2."column"='tic_ric_assign_v2'
          AND name3."column"='org_name'
          AND name4."column"='theraputic_area'
        ORDER BY proposal2.proposal_id;`
```

Would you mind verifying that this is doing what it's intended to do?

**Comment by xu-hao** [comment]
I made a small change:
In the inner join with name2, use tic_ric_assign2 this includes both v1 and v2 values. Otherwise it returns less rows
```
SELECT 
    CAST(proposal2.proposal_id AS INT),
    proposal2.short_name,
    name2.description AS tic_name,
    name3.description AS org_name,
    name4.description AS therapeutic_area,
    proposal2.prop_submit,
    meeting_date_2,
    name.description AS proposal_status,
    DATE_PART('day', meeting_date_2 :: timestamp - proposal2.prop_submit :: timestamp) AS day_count
FROM (SELECT *, COALESCE(proposal.tic_ric_assign_v2, proposal.tic_ric_assign) AS tic_ric_assign2 from proposal) proposal2  
INNER JOIN vote ON proposal2.proposal_id = vote.proposal_id
INNER JOIN name ON name.index=CAST(proposal2.protocol_status AS VARCHAR) AND name."column"='protocol_status'
INNER JOIN name name2 ON name2.index=CAST(proposal2.tic_ric_assign2 AS VARCHAR)
INNER JOIN name name3 ON name3.index=CAST(proposal2.org_name AS VARCHAR)
INNER JOIN study ON proposal2.proposal_id=study.proposal_id
INNER JOIN name name4 ON name4.index=CAST(study.theraputic_area AS VARCHAR)
WHERE proposal2.protocol_status NOT IN ('3', '40')
  AND proposal2.redcap_repeat_instrument IS NULL
  AND proposal2.redcap_repeat_instance IS NULL
  AND meeting_date_2 IS NOT NULL
  AND name2."column"='tic_ric_assign_v2'
  AND name3."column"='org_name'
  AND name4."column"='theraputic_area'
ORDER BY proposal2.proposal_id;
```

**Comment by mbwatson** [comment]
Great, thanks! I'll get this into the dashboard and tick this one off this today.

**Comment by rajshruti18** [comment]
**Days between PAT approval and grant submission (comprehensive only):**
SELECT 
    CAST(proposal2.proposal_id AS INT),
    proposal2.short_name,
    name2.description AS tic_name,
    name3.description AS org_name,
    name4.description AS therapeutic_area,
    proposal2.grant_sub_complete,
    meeting_date_2,
    name.description AS proposal_status,
    DATE_PART('day',  proposal2.grant_sub_complete :: timestamp - meeting_date_2:: timestamp) AS day_count
FROM (SELECT *, COALESCE(proposal.tic_ric_assign_v2, proposal.tic_ric_assign) AS tic_ric_assign2 from proposal) proposal2  
INNER JOIN vote ON proposal2.proposal_id = vote.proposal_id
INNER JOIN name ON name.index=CAST(proposal2.protocol_status AS VARCHAR) AND name."column"='protocol_status'
INNER JOIN name name2 ON name2.index=CAST(proposal2.tic_ric_assign2 AS VARCHAR)
INNER JOIN name name3 ON name3.index=CAST(proposal2.org_name AS VARCHAR)
INNER JOIN study ON proposal2.proposal_id=study.proposal_id
INNER JOIN name name4 ON name4.index=CAST(study.theraputic_area AS VARCHAR)
WHERE proposal2.protocol_status IN ('7', '25')
  AND proposal2.redcap_repeat_instrument IS NULL
  AND proposal2.redcap_repeat_instance IS NULL
  AND meeting_date_2 IS NOT NULL
  AND name2."column"='tic_ric_assign_v2'
  AND name3."column"='org_name'
  AND name4."column"='theraputic_area'
ORDER BY proposal2.proposal_id;

**Comment by rajshruti18** [comment]
**Days between submission to TIN and grant submission (comprehensive only):**
SELECT
CAST(proposal2.proposal_id AS INT),
proposal2.short_name,
name2.description AS tic_name,
name3.description AS org_name,
name4.description AS therapeutic_area,
proposal2.grant_sub_complete,
proposal2.prop_submit,
name.description AS proposal_status,
DATE_PART('day', proposal2.grant_sub_complete :: timestamp - proposal2.prop_submit:: timestamp) AS day_count
FROM (SELECT *, COALESCE(proposal.tic_ric_assign_v2, proposal.tic_ric_assign) AS tic_ric_assign2 from proposal) proposal2
INNER JOIN vote ON proposal2.proposal_id = vote.proposal_id
INNER JOIN name ON name.index=CAST(proposal2.protocol_status AS VARCHAR) AND name."column"='protocol_status'
INNER JOIN name name2 ON name2.index=CAST(proposal2.tic_ric_assign2 AS VARCHAR)
INNER JOIN name name3 ON name3.index=CAST(proposal2.org_name AS VARCHAR)
INNER JOIN study ON proposal2.proposal_id=study.proposal_id
INNER JOIN name name4 ON name4.index=CAST(study.theraputic_area AS VARCHAR)
WHERE proposal2.protocol_status IN ('7', '25')
AND proposal2.redcap_repeat_instrument IS NULL
AND proposal2.redcap_repeat_instance IS NULL
AND proposal2.prop_submit IS NOT NULL
AND name2."column"='tic_ric_assign_v2'
AND name3."column"='org_name'
AND name4."column"='theraputic_area'
ORDER BY proposal2.proposal_id;

**Comment by rajshruti18** [comment]
@mbwatson and @xu-hao There is no services ongoing and grant submission to awarded/approved date; therefore, I wasn't able to write subquery #2 and #5. I used Hao's query as template for #3 and #4. Please let me know if these queries work for you.

**Comment by mbwatson** [comment]
Thanks, @rajshruti18 -- these work great!

**Comment by mbwatson** [comment]
the four dates required for three of these are already coming through with submissions. can we pass the remaining necessary dates through as well? below are requests timespans and the dates currently used to calculate them:

- Submission to PAT approval: `dateSubmitted` to `meetingDate`
- Submission to services ongoing: 
- PAT approval to grant submission: `meetingDate` to `plannedGrantSubmissionDate`
- Submission to TIN to grant submission: 
- Grant submission to awarded/approved: `plannedGrantSubmissionDate` to `fundingStart`

**Comment by rajshruti18** [comment]
@mbwatson Out of the four dates above, just one date i.e. dateSubmitted falls in the 'Proposal' table and you want all these dates in the 'Proposal' table. Is that correct?

**Comment by mbwatson** [comment]
I don't think they need to be put into the proposals table; the others come through with some complex JOIN magic that Hao implemented.

I would just like the remaining necessary dates added to the same proposals query [`query` in this controller](https://github.com/RENCI/dashboard/blob/dev/api/controllers/proposals.js) so they come through with the four dates--`dateSubmitted`, `meetingDate`, plannedGrantSubmissionDate`, and `fundingStart`--that are already returned.

**Comment by rajshruti18** [comment]
Now, I understand what you mean. Thanks for the clarification, @mbwatson. I'll create a list of the remaining necessary dates and post it here for @xu-hao to incorporate into the existing query.

**Comment by rajshruti18** [comment]
@mbwatson @xu-hao  I guess these are the remaining set of dates that are necessary:
plannedSubmissionDate
plannedGrantSubmissionDate
fundingStart
kickOffDateOccurs
workComplete
reportSentToPI
activeProtocolDate
IRBOriginalApproval
siteActivatedDate
studyStartDate

**Comment by mbwatson** [comment]
We need clarification on what "Services Ongoing" means, and we plan to ask in next meeting. Is it possibly the current date?

**Comment by mbwatson** [comment]
We discussed this in our weekly meeting this week.

Right now we cannot answer this question, although maybe moving forward we can start
capturing this information. We were given the okay to hold off on this one, so I'm going to close this for now because the other requests related to date counts are answered.
