### ISSUE TITLE
[queries] Days between (average)

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#19]
Days between (average by TIC and by Therapeutic Area):
- [x]       Submission and PAT approval (all submissions)
- [ ]       Submission and services ongoing (services only – broken out by service)
- [x]       PAT approval and grant submission (comprehensive only)
- [x]       Submission to TIN and grant submission (comprehensive only)
- [x]       Grant submission to awarded/approved (comprehensive only)

**Comment by krobasky** [comment]
@mbwatson, go ahead and close this ticket if the PMD already answers every question.

If the PMD only answers some of the questions posed in this ticket, check those boxes & please work with @rajshruti18 to identify what will be necessary to answer the rest.

If the question itself is unclear, even after speaking with Shruti and @xu-hao, please make a trello card on the 'Challenges' board to ensure we address the question at the next meeting.

**Comment by mbwatson** [comment]
I'm writing to make a note (for myself) that I've reached out to @rajshruti18 for help on this one.

**Comment by xu-hao** [comment]
Days between Submission and PAT approval
```
SELECT 
    AVG(DATE_PART('day', meeting_date_2 :: timestamp - proposal.prop_submit :: timestamp)),
    COUNT(proposal.proposal_id),
    proposal.tic_ric_assign_v2
FROM proposal  
INNER JOIN vote ON proposal.proposal_id = vote.proposal_id
WHERE proposal.protocol_status NOT IN ('3', '40') and proposal.redcap_repeat_instrument is null and proposal.redcap_repeat_instance is null and meeting_date_2 is not null
GROUP BY proposal.tic_ric_assign_v2;

```

**Comment by mbwatson** [comment]
@rajshruti18 @xu-hao  the four dates required for three of these requests are coming through with proposals.

can we pass the remaining necessary dates through as well? below are requests timespans and the dates currently used to calculate them:

- Submission to PAT approval: `dateSubmitted` to `meetingDate`
- Submission to services ongoing: 
- PAT approval to grant submission: `meetingDate` to `plannedGrantSubmissionDate`
- Submission to TIN to grant submission: 
- Grant submission to awarded/approved: `plannedGrantSubmissionDate` to `fundingStart`

**Comment by mbwatson** [comment]
We need clarification on what "Services Ongoing" means, and we plan to ask in next meeting. Is it possibly the current date?

**Comment by mbwatson** [comment]
We discussed this in our weekly meeting this week.

Right now we cannot answer this question, although maybe moving forward we can start
capturing this information. We were given the okay to hold off on this one, so I'm going to close this for now because the other requests related to average date counts are answered.
