### ISSUE TITLE
Approved by PAT for Comprehensive Consultation BY DATE

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#28]
figure out which date to use and add to pmd

**Comment by rajshruti18** [comment]
@krobasky @mbwatson I guess we should use 'meetingDate' field in 'PATMeeting' table with a where condition (WHERE proposalStatus='7') in order to obtain proposals that have been approved for comprehensive consultation by PAT.

**Comment by mbwatson** [comment]
that date sounds appropriate to me--just wanted to not guess and be incorrect. thanks for your insight!

**Comment by mbwatson** [comment]
all four dates are passed through with proposals now for dynamic sorting/grouping in proposal tables.
