### ISSUE TITLE
Feedback #7: Proposal   status- don't love the status from the TIC form

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#53]
"Proposal   status- don't love the status from the TIC form, maybe we could pull from the   last GSS? Need to know how the repeat forms are represented in the REDCap   data"

Dashboard ITem: Proposals
Noted by: JH
Date noted: 4/10

-------------

Hao & Shruti will check for data in redcap that matches the 'Status on Network Dashboard' column in the 'TIN Proposals at a glance ...' spreadsheet.

e.g., values like: 'No   Further Network Support', 'Approved   for Resource(s) Pending Receipt of Funding',...

**Comment by xu-hao** [comment]
I manually looked at them and compared. They do match except:
1. a few proposals that is in the spreadsheet is not showing up in the dashboard
2. the one proposal status is not showing the latest, this could be because of the daily data pulling
3. a few proposals showing in the dashboard is not showing in the spreadsheet

**Comment by krobasky** [comment]
Interesting!
which field matches the 'Status on Network Dashboard' column? is it 'proposal-status'?
Can you record here the proposal IDs for 1., 2. and 3.? We can discuss next week.
thanks!

**Comment by xu-hao** [comment]
The "Status" field in the dashboard

1. 35, 212
2. 491
3. 218, 254, 273, 283, 301 to name a few, there are some others

**Comment by xu-hao** [comment]
3 are proposals without a prop_submit

**Comment by xu-hao** [comment]
3 are proposals without prop_submit (null or ""). 

We'd like to ask the Duke team if they want to filter out all proposals without prop_submit.

Filter by default, Filter on demand, not show at all, or not filter at all.

**Comment by xu-hao** [comment]
3 are proposals without prop_submit (null or ""). 

We'd like to ask the Duke team if they want to 

Filter by default, Filter on demand, not show at all, or not filter at all.

all proposals without prop_submit.

**Comment by xu-hao** [comment]
2 has been updated in the dashboard by the automatic refresh.

**Comment by mbwatson** [comment]
@xu-hao fixed the query to return 35 and 212 in the response. the dashboard will show them, too.

**Comment by mbwatson** [comment]
To update & summarize:

Only number 3 (proposals showing in dashboard not showing in spreadsheet, due to having a `prop_submit` value of `null` or `''`) remains to be addressed.

**Comment by mbwatson** [comment]
@rocsteady888 and I will work this one out by adding a toggle in the Dashboard settings.

**Comment by dcarsey** [comment]
Adding functionality / features to support better usability.  Meanwhile, this is functional and we will show you how to do it.  

workaround:  temporarily ignore blanks at the top.
