### ISSUE TITLE
Feedback #10: " $ amount and Application status"

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#55]
Where is   the " $ amount and the Application status" being populated from? If   there is an error in the budget in the Proposal Intake Form it gets reflected   here so needs to be reconciled. (see 467)

Dashboard Item: Proposals
Noted by: CST
Date noted: 4/15/2019

-----------

proposal ID #467 seems to have the wrong $ amount in the PMD
"Network Support Status Additional Data Elements"

Need to hold for additional information

**Comment by mbwatson** [comment]
Does this refer to the totalBudget?

see: http://stage-pmd.renci.org/api/proposals/467

**Comment by xu-hao** [comment]
@mbwatson I think that is what they are referring to. Can we get from them what the expect value is for that field? I looked into the data. And they recently updated the field from which we pull data. The dashboard has the latest value from that field.

**Comment by mbwatson** [comment]
This value comes from the field we _think_ this data should be coming from.

**Comment by krobasky** [comment]
check the spreadsheet to see how values are conflicting, and to see if there are values matching the spreadsheet in some other field

**Comment by xu-hao** [comment]
It's not in the spreadsheet

**Comment by xu-hao** [comment]
We'd like ask for expected value

**Comment by dcarsey** [comment]
not pulling the money/duration from the latest field; pulling from the outdated form. [Kimberly to update ticket, Shruti to track down field in 'additional data elements' on instrument]

**Comment by rajshruti18** [comment]
Candidate for the field that we are looking for is #3078--- ‘amount_award’ from ‘Network Support Status Additional Data Elements’ instrument in RedCap. This field shows total amount awarded for study. What do you think @xu-hao ?

**Comment by dcarsey** [comment]
Hao trying to get more data from REDCap.  Seems like there are more switches and can make them available to Shruti to look into the data and find potential columns to give us this info.

**Comment by rajshruti18** [comment]
I went through the raw REDCap data given by Hao and it appears that 'amount_award' is the right field for grant $ amount based on the $ amount value that Theresa gave us for proposal#171.
![f10_171](https://user-images.githubusercontent.com/47569410/57953012-e43e8c80-78bc-11e9-9205-dae87fa93134.JPG)

**Comment by rajshruti18** [comment]
'amountAward' field has been added to the schema and is now available to the dashboard. The issue is now resolved.

**Comment by mbwatson** [comment]
`amount_award` is In the `ProposalFunding` table

**Comment by mbwatson** [comment]
I'm not seeing the $8,295,863 for `amountAward` for proposal 171:

```bash
duketic=# select "ProposalID", "amountAward" from "ProposalFunding" where "ProposalID"=171;
 ProposalID | amountAward 
------------+-------------
        171 | 
(1 row)
```

**Comment by xu-hao** [comment]
Probably because the data is old data. Once it refreshes you should see it.
