### ISSUE TITLE
Feedback #11: Where is funding status and approved for resources being pulled from?

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#56]
Where is   the Funding status and approved for resources being pulled from.  Info for 463 not the same pending vs   funded? Suggest details of resources approved

----

Dashboard Item: Proposals
Noted by: CST
Date noted: 4/15/2019

'Funding status' on 'TIN Proposals at a glance' says 'post-award' for PID 463

Michelle Jones (Vanderbilt) keeps a 'log' of changes to the codebook; Theresa can get that change.

What we need to do:
- start pulling the codebook xml and check into github daily so we can start tracking changes
- hunt down the new 'Funding status' field in the redcap data pulls, integrate it into the data, and percolate that up to Matt (Make sure matt knows where to put it in the dashboard.)

**Comment by xu-hao** [comment]
This inconsistency exists in their spreadsheet, the funding status column (post-award) matches the expanded view (funded) and the proposal status column matches status

**Comment by krobasky** [comment]
![image](https://user-images.githubusercontent.com/413166/56522710-a7c57e00-6514-11e9-8c6e-2e864ec3e78c.png)

**Comment by dcarsey** [comment]
Ticket #56
* walk through differences on pid 463 between 'pending receipt of funding' and 'study funded' VS. the spreadsheet
Input error or field difference?
* code in place to track code book changes & need to turn it on

**Comment by dcarsey** [comment]
Theresa will email which statuses need to be removed and what order to ues - follow-up next week;
also - this is just dirty data

**Comment by dcarsey** [comment]
Continually being updated.  When we find a problem, it will get flagged and changed, but we aren't  going in search of these problems.
