### ISSUE TITLE
Feedback #12: grant submission date is incorrect

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#57]
"Dates   are missing where should it be pulled from?    Suggest: 1 Planned grant submission date = original grant submission   date or target submission date on RedCap 2. Actual grant submission date =   Actual grant submission date on RedCap    3. Grant award date= Tentative response date from anticipated funding   source on RedCap"
------
Dashboard Item: Proposal
Noted by: CST
Noted on: 4/15/2019

submission date can be override
"target_grant_1, target_grant_2, target_grant_3..." need to pull just the last date
look for 'date of submission' of hte form and use the latest for the grant submission

**Comment by dcarsey** [comment]
Make sure Matt knows which one to pull.

**Comment by xu-hao** [comment]
I looked into the data. For 146, the date in the spreadsheet is not in the export from the redcap database.

**Comment by dcarsey** [comment]
As long as we're pulling from the most recent batch, then ok.    The updates should be in there now / we should be seeing them.

**Comment by xu-hao** [comment]
look in additional data elements form

**Comment by xu-hao** [comment]
Look for the following text:

N/A (Did not pass OP)

N/A - Awarded resources OP

N/A - Demo

N/A - Pilot

in additional data elements form

**Comment by dcarsey** [comment]
Hao will try to go to REDCap to see if he can get more data.  Point Shruti to where raw exported data is and see if she can find the fields for these strings.

**Comment by dcarsey** [comment]
proposal #146 
proposal submission date vs. grant submission date; both are needed in dashboard; we want Theresa to verify we are pulling date from correct field;

**Comment by rajshruti18** [comment]
As per our discussion with Theresa, the inconsistency was spotted in proposal#146 proposal submission date not grant submission date which has already been resolved. Therefore, this issue can be closed.
