### ISSUE TITLE
Feedback #13: Approved services value is incorrect - data issue or dashboard issue?

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#58]
Information must be consistent and supportive. Approved for resources with clock should agree with info under Approved services instead of N/A

---------

Dashboard Item: Proposals
Noted by: CST
Date noted: 4/15/2019

Example:
proposal ID 463

If 'Approved for Resource(s) Pending Receipt of Funding', then there should be something under 'approved services', like 'central IRB', but not just N/A

Is this a data problem, or is it looking up wrong? - confirm the raw data has an N/A, and if so, let Theresa know at the next meeting.
If there's not an N/A in the raw data, check the database, if there's an N/A there, tell how so he can fix the pipeline.
If there's not an N/A in the database, tell Matt so he can fix the dashboard.

**Comment by mbwatson** [comment]
Here's the related query results on a relatively recent snapshot of the database:

```
duketic=# select * from "Proposal_ServicesApproved";                                        
 ProposalID |   servicesApproved    
------------+-----------------------
         31 | services_approved___2
         25 | services_approved___4
         25 | services_approved___5
         25 | services_approved___6
         25 | services_approved___7
         53 | services_approved___4
        107 | services_approved___2
        125 | services_approved___2
        162 | services_approved___3
        162 | services_approved___4
        162 | services_approved___5
        157 | services_approved___4
        157 | services_approved___5
        108 | services_approved___3
        108 | services_approved___4
        108 | services_approved___5
         74 | services_approved___4
         74 | services_approved___5
         69 | services_approved___6
(19 rows)
```

You can cross-reference this data here: [http://localhost:3030/proposals](http://localhost:3030/proposals). Is there more services (should change to "resources" per issue #13) approved information elsewhere?

**Comment by mbwatson** [comment]
@xu and i confirmed that this is a data issue

**Comment by dcarsey** [comment]
**Adding to the documentation on this issue:**

Which field is data pulled from in column AG from TIN Proposals at a glance?
(look at pid 146: data submitted is 2017-04-26 in db, but in spreadsheet it's different)
in the ss: it's the data that the proposal was submitted to the network. From the 'assigned tic or ric form' in redcap.
Theresa says' we're pulling the right date; Michelle might be pulling from something else.
Theresa is find out where Michelle is pulling dates from.

**Theresa writes to Michelle:**

Hi Michelle,

Can you clarify where the date pulls from for the ‘Date Submitted’ column in the GSS report export from the dashboard?

For proposal 146 – date submitted is 5/22/2017; in the database (TIC/RIC assigned) the date submitted is 4/26/2017.

Thanks for your help with this.

Best regards,

Theresa Jasion

**Michelle responds:**

Hi Theresa,

This proposal was submitted on 05/22/17 according to survey completion logging. That field that has the wrong date was manually entered (I actually filled out the field) and the date is incorrect.

I’ve corrected the date. Thank you for bringing it to my attention. I believe this field auto-populates now so we shouldn’t have this issue going forward.

Thanks,
Michelle

**Theresa says to RENCI:**

FYI - - the date has been ‘fixed’ (and it is still manually entered).  If you find others, I guess let me know and we’ll get her to manually fix them (unless ya’ll can access the survey completion log) . . . painful process.

Thanks for letting us know.

Best regards,

Theresa Jasion

**Comment by mbwatson** [comment]
This seems to be fixed, but we'll leave this open until we are sure there are no other issues.
