### ISSUE TITLE
Feedback #13, additional: Don't use 'services' on the dashboard - TIN isn't a CRO

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#59]
Don't use 'services' on the dashboard - TIN isn't a CRO

Change 'services' to 'resources'
e.g., 'Requested Services' , 'Approved Services' to '... Resources'

**Comment by mbwatson** [comment]
I've made the changes on the frontend the api layers and will roll it out in the next version.

@xu-hao, @rajshruti18 To keep them consistent and not cause future confusion, we perhaps should change the database columns to match this change.
