### ISSUE TITLE
Feedback #15: The drop-down menus are not very user friendly	

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#61]
The   drop-down menus are not very user friendly
--
Dashboard Item: Collaborations
Noted by: MB
Date noted: 4/15/2019

**Comment by davidborland** [comment]
We did not actually discuss this today, right?

**Comment by krobasky** [comment]
Right. It's on Trello to discuss next week, and I thought I'd get ahead by making github tickets today :)

**Comment by davidborland** [comment]
That's what I assumed, but just wanted to check.

**Comment by krobasky** [comment]
addressed today - dropdowns seemed to get broken on chrome

**Comment by mbwatson** [comment]
this is the same issue as #51

**Comment by mbwatson** [comment]
The styling issue we observed in our 04/23/2019 meeting was an issue related to a Node module that has been sorted out (see #51).

We need to check with them to see if that fixes the concerns they were having.

If not, more details would be helpful, such as answers to some of the following questions:

- what about it makes the menus not user-friendly
- what would make the menus more user-friendly
- is there an alternative in mind that accomplishes the same task, e.g., search box?
- what are some other sites' menus that you like?
