### ISSUE TITLE
Feedback #2:  Opening screen - Change the order of the statuses; some statuses belong to old process and may be deleted.

### ISSUE THREAD

**Issue by dcarsey** [RENCI/dashboard#66]
WAITING FOR DUKE TIC to provide the re-ordered listing of statuses.

**Comment by mbwatson** [comment]
1. Which statuses?

2. Are we removing them at the database level or filtering these out at the client level? Note that the more specialization that leaks into the front-end, the less generalizable the application becomes.

**Comment by dcarsey** [comment]
Great questions. 

1.  The statuses that are in the legend on the far right side of the front page of the dashboard.   The ones that you moved so that they wouldn't be overlapping with the bar graph?
2.  I believe it's only for the labeling for that particular table that they want to remove some of the statuses, etc..  I don't think this spills over into the other parts of the data / mapping, etc.
 ** Please let me know if this was not clear ! **

**Comment by mbwatson** [comment]
Thanks! So we're just waiting for Duke to tell us (1) which statuses they would like removed from this chart and (2) the order they'd like them to be in. is that right?

**Comment by dcarsey** [comment]
Oui.  I sent the request .....

[https://media.giphy.com/media/UxREcFThpSEqk/giphy.gif]

**Comment by mbwatson** [comment]
We asked about this on 4/30; the vote is still out on this.

**Comment by mbwatson** [comment]
1. Ready for initial consult and approved for initial consult can we change the ‘tag’ to Initial Consult Ongoing
2. Approved for resources pending funding
3. Approved for Resources
4. Approved for Comprehensive Consultation
5.Resources complete
6. Comprehensive consult complete grant submitted
7. Ready for Implementation – Can we change the ‘tag’ to Implementation Ongoing
8. No further network support
9. Withdrawn by PI and  Withdrawn by PI post award –Can we ‘tag’ as Withdrawn by PI

**Comment by mbwatson** [comment]
These are the groupings mentioned. They are listed here in the following format:

- Display Name
    + status 1 to be grouped under this name
    + status 2 to be grouped under this name

Status Groupings:

- Initial Consult Ongoing
    + Approved for Initial Consultation
    + Ready for Initial Consultation
- Approved for Resources Pending Funding
    + Approved for Resource(s) Pending Receipt of Funding
- Resources Ongoing
    + Approved for Resource(s)
- Comprehensive Consultation Ongoing
    + Approved for Comprehensive Consultation
- Resources Complete
    + Resource(s) Complete
- Comprehensive Consult Complete Grant Submitted
    + Comprehensive Complete - Grant Submitted
- Implementation Ongoing
    + Ready for Implementation
- No Further Network Support
    + No Further Network Support
- Withdrawn by PI
    + Withdrawn by PI
    + Withdrawn by PI post-award

There are ten unmentioned statuses (listed below). We should see if they can also be grouped or if they should remain as is. Some of them are perhaps obsolete.

- Submitted
- Pending Submission
- Returned to Investigator
- Under Review
- Re-Submitted
- Pending Re-submission
- Ready for NCATS Review
- Not Approved
- On Hold
- Approved for Network Support
