### ISSUE TITLE
Feedback #1:  Proposals tab - need to be able to sort the proposals by 2 levels.

### ISSUE THREAD

**Issue by dcarsey** [RENCI/dashboard#67]
They  may just need to be taught how to do this.  However, when we demoed it, it didn't work to sort by TIC/RIC.

**Comment by mbwatson** [comment]
This can be done by rouping by first column, then sort by second criterion.

Drag column name, say _Assigned TIC/RIC_,  to the gray area in the header labeled "Drag headers here to group by," Then click the second column to sort the grouped proposals by that column.

**Comment by mbwatson** [comment]
we confirmed this complete in our 02/23/2019 meeting.
