### ISSUE TITLE
Feedback #7 additional:  Why are there proposals missing in Theresa's spreadsheet?

### ISSUE THREAD

**Issue by dcarsey** [RENCI/dashboard#73]
Description of problem:
From github ticket: #53
1. a few proposals that is in the spreadsheet is not showing up in the dashboard
35, 212
2. the one proposal status is not showing the latest, this could be because of the daily data pulling
491
3. a few proposals showing in the dashboard is not showing in the spreadsheet
218, 254, 273, 283, 301 to name a few, there are some others

Theresa: Not on the list because: "pending submission"
Hao: they all have no submission date (all others do)
make default reports not show any proposals without submission date.
[Kimberly - update ticket, assign to david and Matt]

**Comment by mbwatson** [comment]
i'm closing this, and we can use the other feedback #7 to discuss this issue
