### ISSUE TITLE
Procure DukeTIC study data for metrics report

### ISSUE THREAD

**Issue by dcarsey** [RENCI/dashboard#74]
SPIRRIT, COVET, and STRESS (They will talk to Utah.)

**Comment by dcarsey** [comment]
COVET - will get data but the project is likely being terminated;  others forthcoming; Test data:  Utah and JHU = unrelated to a study.

**Comment by dcarsey** [comment]
COVET - funding has been pulled.

**Comment by krobasky** [comment]
SPIRRIT & STRESS

**Comment by krobasky** [comment]
we have SPIRRIT
will still pull-down COVET
