### ISSUE TITLE
Minor warnings (ununsed vars) in proposals network

### ISSUE THREAD

**Issue by renciweb** [RENCI/dashboard#8]
webpackHotDevClient.js:120 ./src/components/Visualizations/proposalsSankey.js
  Line 14:  'event' is assigned a value but never used  no-unused-vars

and

webpackHotDevClient.js:120 ./src/components/Visualizations/proposalsNetwork.js
  Line 9:   'innerWidth' is assigned a value but never used   no-unused-vars
  Line 10:  'innerHeight' is assigned a value but never used  no-unused-vars
  Line 13:  'event' is assigned a value but never used        no-unused-vars

**Comment by davidborland** [comment]
Fixed this.
