### ISSUE TITLE
when I click on "submissions by month" column I would like to see a simple list of proposals and who they're assigned to (low priority)

### ISSUE THREAD

**Issue by krobasky** [RENCI/dashboard#94]

**Comment by dcarsey** [comment]
![image](https://user-images.githubusercontent.com/47784445/59635332-f95a4580-911e-11e9-8ff2-b25ec7deac50.png)

**Comment by mbwatson** [comment]
sounds right. then this is a duplicate, so I'm closing this one in lieu of #77.
